### ISSUE TITLE
ClassCastException: MyApplication cannot be cast to androidx.appcompat.app.AppCompatActivity

### ISSUE THREAD

**Issue by fm-eb** [nuonveyo/AutoRefreshNetworkConnection#3]
Hey there, thanks for this lib!

One issue though: You should not ask for a `Context` via the `getContext` method, when you really want an `AppCompatActivity`.

I wanted to initialize the library with my Application instance and got the Exception in the title of this issue. Maybe rewrite the method of `StopReceiveDisconnectedListener` to `getAppCompatActivity()` or find a way to make the library work with only a `Context`.

**Comment by nuonveyo** [comment]
What error have you got exactly during initialize and what is your purpose to use this library?

**Comment by fm-eb** [comment]
Hey, I get the same error message mentioned in the title:

`ClassCastException: MyApplication cannot be cast to androidx.appcompat.app.AppCompatActivity`

The method name `getContext` implies that a `Context` is enough. But when you look into the code of `CheckNetworkConnectionHelper.java` you see the following lines:

```
mCurrentContext = listener.getContext();
AppCompatActivity appCompatActivity = (AppCompatActivity) mCurrentContext;
```

So if I pass a `Context` in the form of a Fragment/Application/View into your library, the library crashes.

I see two solutions:

1. Simple solution: rename the method from `getContext()` to `getAppCompatActivity()`
2. Proper solution: try to refactor the llibrary so that a `Context` is enough for it to work. Not sure if this is possible.

**Comment by nuonveyo** [comment]
Thank you!
Yes, It is better to refactor some code for improvement.
